### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by amastaneh** [arashmanteghi/simptip#16]
Arash jan,
Would you please add `simptip` [NuGet](http://nuget.org) package. It's really useful for Microsoft software developers. You can find a less than a hour solution to build and deploy NuGet package in here http://docs.nuget.org/docs/creating-packages/using-a-gui-to-build-packages

Thank you ;-)

**Comment by arashmanteghi** [comment]
Hi
As soon as possible I'll do it and inform you.
Best wishes :)
