### ISSUE TITLE
Add link inside tooltip

### ISSUE THREAD

**Issue by 70hundert** [arashmanteghi/simptip#17]
Hello there!

Is it possible to place a link inside the tooltip, like

<span class="simptip-position-right simptip-movable simptip-multiline simptip-info" data-tooltip="To view this file you need the free <a href="http://get.adobe.com/de/reader/" target="_blank">Adobe Acrobat Reader</a>. Click to open.">

Greetings from Germany!

**Comment by arashmanteghi** [comment]
Hi,

Unfortunately, you can't use HTML tag in this version of Simptip. Maybe next version :)

Kind regards

**Comment by 70hundert** [comment]
Thank you for your reply!
