### ISSUE TITLE
Tooltip on Image Hover

### ISSUE THREAD

**Issue by subirpal** [arashmanteghi/simptip#18]
Hi Arash,

Thanks for the nice tooltip. Is is possible to apply the tooltip on image hover? I used it but unfortunately not working.

Thanks.

**Comment by arashmanteghi** [comment]
Hi,

You can write IMG tag in a SPAN container, then use Simptip on SPAN tag :

```html
<span  class="simptip-position-top" data-tooltip="I'm in top">
  <img src="image.jpg">
</span> 
```
Thanks

**Comment by subirpal** [comment]
Thanks for replying...I knew the tricks and m going to use it if can't find any solution... ;)
